# Generated by Django 4.1.7 on 2023-04-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tag_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
